/**
 * @file planning_pipeline_unit_test.cpp
 * @brief Validates vendor-independent planning pipeline orchestration.
 */

#include <chrono>
#include <cstdlib>
#include <memory>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

#include <humanoid/bt/ActionNode.h>
#include <humanoid/bt/BehaviorTree.h>
#include <humanoid/bt/BehaviorTreeFactory.h>
#include <humanoid/bt/BehaviorTreeRuntime.h>
#include <humanoid/bt/SequenceNode.h>
#include <humanoid/common/Status.hpp>
#include <humanoid/core/Command.h>
#include <humanoid/core/CommandType.h>
#include <humanoid/logging/Logger.hpp>
#include <humanoid/mission/Mission.h>
#include <humanoid/mission/MissionStep.h>
#include <humanoid/planner/IPlanner.h>
#include <humanoid/planner/PlanningPipeline.h>
#include <humanoid/runtime/Blackboard.h>
#include <humanoid/runtime/ExecutionState.h>
#include <humanoid/runtime/ResourceManager.h>
#include <humanoid/runtime/RuntimeScheduler.h>

namespace {

void Require(bool condition) {
  if (!condition) {
    std::abort();
  }
}

[[nodiscard]] humanoid::common::Status InvalidArgument(std::string message) {
  return humanoid::common::Status::error(humanoid::common::StatusCode::kInvalidArgument,
                                         std::move(message));
}

class TestLogger final : public humanoid::logging::ILogger {
public:
  humanoid::common::Status log(const humanoid::logging::LogMessage& message) override {
    messages.push_back(message.text());
    return humanoid::common::Status::ok();
  }

  [[nodiscard]] bool isEnabled(humanoid::logging::LogLevel) const noexcept override { return true; }

  std::vector<std::string> messages;
};

enum class PlannerMode { Success, FailureWithoutArtifacts, Throwing };

class TestPlanner final : public humanoid::planner::IPlanner {
public:
  explicit TestPlanner(PlannerMode mode,
                       humanoid::common::Status validation_status = humanoid::common::Status::ok())
      : mode_(mode), validation_status_(std::move(validation_status)) {}

  [[nodiscard]] humanoid::planner::PlanningResult
  Plan(const humanoid::planner::PlanningRequest& request) override {
    ++plan_calls_;

    if (mode_ == PlannerMode::Throwing) {
      throw std::runtime_error{"planner failure"};
    }

    humanoid::planner::PlanningResult result;
    if (mode_ == PlannerMode::FailureWithoutArtifacts) {
      result.status = humanoid::planner::GoalStatus::Failed;
      result.diagnostics.push_back({humanoid::planner::PlanningDiagnosticSeverity::Error,
                                    "test.failed", "test planner failed"});
      return result;
    }

    result.status = humanoid::planner::GoalStatus::Planned;
    result.mission = MakeMission(request.goal.id);
    result.behaviorTree = MakeBehaviorTree();
    result.diagnostics.push_back({humanoid::planner::PlanningDiagnosticSeverity::Info,
                                  "test.planned", "test planner generated artifacts"});
    return result;
  }

  [[nodiscard]] humanoid::common::Status
  ValidatePlan(const humanoid::planner::PlanningResult&) const override {
    ++validation_calls_;
    return validation_status_;
  }

  [[nodiscard]] humanoid::common::Status CancelPlan() override {
    cancelled_ = true;
    return humanoid::common::Status::ok();
  }

  [[nodiscard]] humanoid::planner::PlannerCapabilities GetCapabilities() const override {
    humanoid::planner::PlannerCapabilities capabilities;
    capabilities.plannerId = "test-planner";
    capabilities.name = "Test Planner";
    capabilities.description = "Hardware-free planner for planning pipeline validation";
    capabilities.kind = humanoid::planner::PlannerKind::Custom;
    capabilities.supportedGoalTypes = {humanoid::planner::GoalType::Custom};
    capabilities.supportsMissionOutput = true;
    capabilities.supportsBehaviorTreeOutput = true;
    capabilities.supportsPlanValidation = true;
    capabilities.supportsCancellation = true;
    return capabilities;
  }

  [[nodiscard]] std::uint32_t planCalls() const noexcept { return plan_calls_; }

  [[nodiscard]] std::uint32_t validationCalls() const noexcept { return validation_calls_; }

  [[nodiscard]] bool cancelled() const noexcept { return cancelled_; }

private:
  [[nodiscard]] static humanoid::mission::Mission MakeMission(humanoid::planner::GoalId goal_id) {
    humanoid::mission::Mission mission;
    mission.id = goal_id + 1000U;
    mission.name = "Planning Pipeline Mission";
    mission.description = "Mission generated by planning pipeline unit test";
    mission.version = "1.0";
    mission.author = "humanoid-core";

    humanoid::mission::MissionStep step;
    step.id = 1U;
    step.name = "Synthetic step";
    step.command.id = goal_id + 2000U;
    step.command.type = humanoid::core::CommandType::Custom;
    mission.steps.push_back(std::move(step));
    return mission;
  }

  [[nodiscard]] static std::unique_ptr<humanoid::bt::BehaviorTree> MakeBehaviorTree() {
    humanoid::bt::BTChildren children;
    children.push_back(
        std::make_unique<humanoid::bt::ActionNode>("PipelineAction", [](humanoid::bt::BTContext&) {
          return humanoid::bt::BTStatus::Success;
        }));
    return std::make_unique<humanoid::bt::BehaviorTree>(
        std::make_unique<humanoid::bt::SequenceNode>("PipelineSequence",
                                                     humanoid::bt::SequenceMemoryPolicy::Stateless,
                                                     std::move(children)));
  }

  PlannerMode mode_;
  humanoid::common::Status validation_status_;
  std::uint32_t plan_calls_{0U};
  mutable std::uint32_t validation_calls_{0U};
  bool cancelled_{false};
};

[[nodiscard]] humanoid::planner::PlanningRequest MakeRequest() {
  humanoid::planner::PlanningRequest request;
  request.goal.id = 9001U;
  request.goal.type = humanoid::planner::GoalType::Custom;
  request.goal.description = "validate planning pipeline";
  request.robotCapabilities.supportsLifecycle = true;
  request.robotCapabilities.supportsConnectionManagement = true;
  request.robotCapabilities.supportsStateFeedback = true;
  return request;
}

void VerifyPrimaryPlanningValidationMetricsAndLogging() {
  auto planner = std::make_shared<TestPlanner>(PlannerMode::Success);
  auto logger = std::make_shared<TestLogger>();
  humanoid::planner::PlanningPipeline pipeline{planner, {}, {}, logger};

  humanoid::planner::PlanningPipelineResult result = pipeline.Execute(MakeRequest());

  Require(result.status.isOk());
  Require(!result.usedFallback);
  Require(result.planningResult.hasMission());
  Require(result.planningResult.hasBehaviorTree());
  Require(result.planningResult.mission->isValid());
  Require(planner->planCalls() == 1U);
  Require(planner->validationCalls() == 1U);
  Require(!logger->messages.empty());

  const humanoid::planner::PlanningPipelineMetrics metrics = pipeline.GetMetrics();
  Require(metrics.requests == 1U);
  Require(metrics.primaryPlannerAttempts == 1U);
  Require(metrics.planned == 1U);
  Require(metrics.failed == 0U);
}

void VerifyFallbackAfterPrimaryFailure() {
  auto primary = std::make_shared<TestPlanner>(PlannerMode::FailureWithoutArtifacts);
  auto fallback = std::make_shared<TestPlanner>(PlannerMode::Success);
  humanoid::planner::PlanningPipeline pipeline{primary, fallback};

  humanoid::planner::PlanningPipelineResult result = pipeline.Execute(MakeRequest());

  Require(result.status.isOk());
  Require(result.usedFallback);
  Require(primary->planCalls() == 1U);
  Require(fallback->planCalls() == 1U);

  const humanoid::planner::PlanningPipelineMetrics metrics = pipeline.GetMetrics();
  Require(metrics.fallbackPlannerAttempts == 1U);
  Require(metrics.fallbackSucceeded == 1U);
  Require(metrics.planned == 1U);
}

void VerifyValidationFailure() {
  auto planner = std::make_shared<TestPlanner>(
      PlannerMode::Success, InvalidArgument("generated plan rejected by validator"));
  humanoid::planner::PlanningPipeline pipeline{planner};

  humanoid::planner::PlanningPipelineResult result = pipeline.Execute(MakeRequest());

  Require(!result.status.isOk());
  Require(result.planningResult.hasMission());
  Require(result.planningResult.hasBehaviorTree());

  const humanoid::planner::PlanningPipelineMetrics metrics = pipeline.GetMetrics();
  Require(metrics.validationFailures == 1U);
  Require(metrics.failed == 1U);
  Require(metrics.planned == 0U);
}

void VerifyInvalidRequestRejected() {
  auto planner = std::make_shared<TestPlanner>(PlannerMode::Success);
  humanoid::planner::PlanningPipeline pipeline{planner};

  humanoid::planner::PlanningPipelineResult result =
      pipeline.Execute(humanoid::planner::PlanningRequest{});

  Require(!result.status.isOk());
  Require(result.planningResult.status == humanoid::planner::GoalStatus::Rejected);
  Require(planner->planCalls() == 0U);

  const humanoid::planner::PlanningPipelineMetrics metrics = pipeline.GetMetrics();
  Require(metrics.rejected == 1U);
}

void VerifyRuntimeSubmission() {
  auto scheduler = std::make_shared<humanoid::runtime::RuntimeScheduler>(
      humanoid::runtime::RuntimeSchedulerOptions{8U, 1U, 8U});
  auto blackboard = std::make_shared<humanoid::runtime::Blackboard>();
  auto resources = std::make_shared<humanoid::runtime::ResourceManager>();
  auto factory = std::make_shared<humanoid::bt::BehaviorTreeFactory>();
  auto runtime = std::make_shared<humanoid::bt::BehaviorTreeRuntime>(scheduler, blackboard,
                                                                     resources, factory);

  auto planner = std::make_shared<TestPlanner>(PlannerMode::Success);
  humanoid::planner::PlanningPipeline pipeline{planner, {}, runtime};

  humanoid::planner::PlanningPipelineOptions options;
  options.submitBehaviorTreeToRuntime = true;
  options.runtimeOptions.executionId = 9301U;
  options.runtimeOptions.tickInterval = std::chrono::milliseconds{1};

  humanoid::planner::PlanningPipelineResult result =
      pipeline.Execute(MakeRequest(), std::move(options));

  Require(result.status.isOk());
  Require(result.runtimeHandle.has_value());
  Require(result.runtimeHandle->jobId == 9301U);
  Require(!result.planningResult.hasBehaviorTree());
  Require(result.runtimeHandle->result.get().state == humanoid::runtime::ExecutionState::Completed);

  const humanoid::planner::PlanningPipelineMetrics metrics = pipeline.GetMetrics();
  Require(metrics.runtimeSubmissions == 1U);
  Require(metrics.runtimeSubmissionFailures == 0U);
  Require(metrics.planned == 1U);

  scheduler->Shutdown();
}

} // namespace

int main() {
  VerifyPrimaryPlanningValidationMetricsAndLogging();
  VerifyFallbackAfterPrimaryFailure();
  VerifyValidationFailure();
  VerifyInvalidRequestRejected();
  VerifyRuntimeSubmission();
  return EXIT_SUCCESS;
}
