replicaCount: 1

image:
  repository: humanoid-core
  tag: 1.0.1-validation
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  HUMANOID_CORE_ENABLE_CLOUD: "true"
  HUMANOID_CORE_API_VERSION: "v1"
