apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-cloud
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-cloud
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-cloud
    spec:
      containers:
        - name: cloud
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- range $name, $value := .Values.env }}
            - name: {{ $name }}
              value: "{{ $value }}"
            {{- end }}
