#pragma once

/**
 * @file core.hpp
 * @brief Public umbrella header for humanoid-core.
 */

#include <humanoid/adapters/IRobotAdapter.h>
#include <humanoid/adapters/IRobotFactory.h>
#include <humanoid/adapters/Result.h>
#include <humanoid/ai/ILLMProvider.h>
#include <humanoid/ai/LLMCapabilities.h>
#include <humanoid/ai/LLMRequest.h>
#include <humanoid/ai/LLMResponse.h>
#include <humanoid/bt/ActionNode.h>
#include <humanoid/bt/BTContext.h>
#include <humanoid/bt/BTNode.h>
#include <humanoid/bt/BTStatus.h>
#include <humanoid/bt/BehaviorTree.h>
#include <humanoid/bt/BehaviorTreeFactory.h>
#include <humanoid/bt/BehaviorTreeRuntime.h>
#include <humanoid/bt/CommandNode.h>
#include <humanoid/bt/CompositeNode.h>
#include <humanoid/bt/ConditionNode.h>
#include <humanoid/bt/DecoratorNode.h>
#include <humanoid/bt/DelayNode.h>
#include <humanoid/bt/FailerNode.h>
#include <humanoid/bt/InverterNode.h>
#include <humanoid/bt/LimiterNode.h>
#include <humanoid/bt/MissionNode.h>
#include <humanoid/bt/ParallelNode.h>
#include <humanoid/bt/RepeatNode.h>
#include <humanoid/bt/RetryNode.h>
#include <humanoid/bt/SelectorNode.h>
#include <humanoid/bt/SequenceNode.h>
#include <humanoid/bt/SucceederNode.h>
#include <humanoid/bt/TimeoutNode.h>
#include <humanoid/bt/TreeLoader.h>
#include <humanoid/bt/TreeParser.h>
#include <humanoid/bt/TreeValidator.h>
#include <humanoid/bt/WaitNode.h>
#include <humanoid/common/LifecycleState.hpp>
#include <humanoid/common/Status.hpp>
#include <humanoid/common/Version.hpp>
#include <humanoid/configuration/ConfigManager.hpp>
#include <humanoid/configuration/ConfigValue.hpp>
#include <humanoid/configuration/Configuration.hpp>
#include <humanoid/core/Command.h>
#include <humanoid/core/CommandDispatcher.h>
#include <humanoid/core/CommandExecutionPipeline.h>
#include <humanoid/core/CommandPriority.h>
#include <humanoid/core/CommandQueue.h>
#include <humanoid/core/CommandResult.h>
#include <humanoid/core/CommandStatus.h>
#include <humanoid/core/CommandType.h>
#include <humanoid/core/CoreContext.hpp>
#include <humanoid/core/RobotAdapter.h>
#include <humanoid/core/RobotState.hpp>
#include <humanoid/core/RobotStateManager.hpp>
#include <humanoid/core/RuntimeMetadata.hpp>
#include <humanoid/core/SafetyValidator.h>
#include <humanoid/diagnostics/DiagnosticController.hpp>
#include <humanoid/diagnostics/DiagnosticManager.hpp>
#include <humanoid/diagnostics/DiagnosticRecord.hpp>
#include <humanoid/diagnostics/DiagnosticStatus.hpp>
#include <humanoid/gesture/GestureController.hpp>
#include <humanoid/gesture/GestureManager.hpp>
#include <humanoid/logging/LogLevel.hpp>
#include <humanoid/logging/LogMessage.hpp>
#include <humanoid/logging/LogSink.hpp>
#include <humanoid/logging/Logger.hpp>
#include <humanoid/logging/LoggerManager.hpp>
#include <humanoid/mission/ConditionEvaluator.h>
#include <humanoid/mission/DelayStep.h>
#include <humanoid/mission/LoopPolicy.h>
#include <humanoid/mission/Mission.h>
#include <humanoid/mission/MissionCondition.h>
#include <humanoid/mission/MissionEvent.h>
#include <humanoid/mission/MissionExecutor.h>
#include <humanoid/mission/MissionLoader.h>
#include <humanoid/mission/MissionMetadata.h>
#include <humanoid/mission/MissionParser.h>
#include <humanoid/mission/MissionResult.h>
#include <humanoid/mission/MissionStatus.h>
#include <humanoid/mission/MissionStep.h>
#include <humanoid/mission/MissionValidator.h>
#include <humanoid/mission/RetryPolicy.h>
#include <humanoid/mission/TimeoutPolicy.h>
#include <humanoid/mission/WaitStep.h>
#include <humanoid/motion/MotionController.hpp>
#include <humanoid/motion/MotionManager.hpp>
#include <humanoid/motion/MotionMode.hpp>
#include <humanoid/network/Endpoint.hpp>
#include <humanoid/network/NetworkManager.hpp>
#include <humanoid/network/TransportProtocol.hpp>
#include <humanoid/perception/DetectionResult.h>
#include <humanoid/perception/IInferenceEngine.h>
#include <humanoid/perception/InferenceRequest.h>
#include <humanoid/perception/InferenceResult.h>
#include <humanoid/perception/ModelManager.h>
#include <humanoid/perception/PerceptionPipeline.h>
#include <humanoid/perception/Sensor.h>
#include <humanoid/perception/SensorCapabilities.h>
#include <humanoid/perception/SensorFactory.h>
#include <humanoid/perception/SensorFrame.h>
#include <humanoid/perception/SensorFusion.h>
#include <humanoid/perception/SensorManager.h>
#include <humanoid/perception/SensorState.h>
#include <humanoid/perception/SensorType.h>
#include <humanoid/planner/Goal.h>
#include <humanoid/planner/GoalPriority.h>
#include <humanoid/planner/GoalStatus.h>
#include <humanoid/planner/GoalType.h>
#include <humanoid/planner/IPlanner.h>
#include <humanoid/planner/PlannerFactory.h>
#include <humanoid/planner/PlannerRegistry.h>
#include <humanoid/planner/PlanningPipeline.h>
#include <humanoid/planner/PlanningRequest.h>
#include <humanoid/planner/PlanningResult.h>
#include <humanoid/planner/RuleBasedPlanner.h>
#include <humanoid/robot/Robot.hpp>
#include <humanoid/robot/RobotAdapter.hpp>
#include <humanoid/robot/RobotManager.hpp>
#include <humanoid/runtime/Blackboard.h>
#include <humanoid/runtime/Cancellation.h>
#include <humanoid/runtime/ExecutionContext.h>
#include <humanoid/runtime/ExecutionContextId.h>
#include <humanoid/runtime/ExecutionMetadata.h>
#include <humanoid/runtime/ExecutionScope.h>
#include <humanoid/runtime/ExecutionState.h>
#include <humanoid/runtime/ResourceManager.h>
#include <humanoid/runtime/RuntimeScheduler.h>
#include <humanoid/safety/SafetyController.hpp>
#include <humanoid/safety/SafetyManager.hpp>
#include <humanoid/safety/SafetyState.hpp>
#include <humanoid/services/TelemetryService.h>
#include <humanoid/utilities/Filesystem.hpp>
#include <humanoid/utilities/ScopeExit.hpp>
#include <humanoid/utilities/Time.hpp>
